---
title: "cm008 Exercises"
output: github_document
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
#install.packages("nycflights13")
suppressPackageStartupMessages(library(nycflights13))
```

## Types of join

```{r}
#create two data.frames named a and b
(a <- data.frame(x1 = LETTERS[1:3], x2 = 1:3))
(b <- data.frame(x1 = LETTERS[c(1,2,4)], x3 = c("T", "F", "T")))

#left_join: Join matching rows from b to a
left_join(a, b, by = "x1")

#right_join: Join matching rows from a to b.
right_join(a, b, by = "x1")

#inner_join: Join data. Retain only rows in both sets
inner_join(a, b, by = "x1")

#full_join: Join data. Retain all values, all rows.
full_join(a, b, by = "x1")

#what happen if we do not specify by option?
left_join(a, b)

#what happen if we specify two different variables from two data.frames?
left_join(a, b, by = c("x1" = "x3"))

#what happen if two columns have the identical names
(c <- data.frame(x1 = c(LETTERS[1:2],"x"), x2 = c(1,4,5)))
inner_join(a, c)
```


## `nycflights13` dataset has four tibbles e.g., `flights`, `airports`, `planes`.

```{r, eval=FALSE}
#check the tibbles included in `nycflights13` package
class(flights)
colnames(flights)
colnames(airports)
colnames(planes)

# Drop unimportant variables so it's easier to understand the join results. Also take first 20000 rows to run it faster.
#flights2 <- flights %>% select(year:day, hour, origin, dest, tailnum, carrier)
flights2 <- flights[1:20000,] %>% select(year, tailnum, carrier)
dim(flights2)

#add airline names from `airlines` by carrier 
flights2 %>% 
  left_join(airlines) 

#flights2 %>% left_join(weather)
```


#misc
The coloured column represents the “key” variable: these are used to match the rows between the tables. 

A join is a way of connecting each row in x to zero, one, or more rows in y.

Duplicates in one of the tables

Other implementations


